print ("my name is Thu Ya Tun")
print ("********  **    **     ******")
print ("********   **  **      ******")
print ("   **        **          **")
print ("   **        **          **")
print ("   **        **          **")
